### PR TITLE
Mongoid5

### PR DESCRIPTION
**Pull request by lukaso**
Updates the pull request with mongoid 5 support. This ideally fixes the concern raised by @wulfeld in https://github.com/adacosta/mongoid_rails_migrations/pull/34

### CODE REVIEW

**Comment by lukaso** [comment]
Whoops, misspelled handle: @wulffeld.

**Comment by wulffeld** [comment]
Looks good to me.

**Comment by kbogtob** [comment]
+1

**Comment by chaomao** [comment]
@adacosta , can we merge this pr and release new version?

**Comment by adacosta** [comment]
@chaomao I merged it to master. Can you point your code to master and confirm it works well? If so, I'll bump the version and release it.

**Comment by tstrass** [comment]
@adacosta I pointed my code to master and it worked running a simple `db:migrate` and `db:rollback`. Are you still intending to tag a release?

**Comment by chao-xian** [comment]
Has this been released yet? I've also hit this problem.

**Pull request merged**
